version: "3"

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github_log
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-airflow:2.9.1-python3.10
    env_file:
      - airflow.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./etls:/opt/airflow/etls
      - ./pipelines:/opt/airflow/pipelines
      - ./utils:/opt/airflow/utils
      - ./requirements.txt:/requirements.txt
      - ./config:/opt/airflow/config
    depends_on:
      - postgres
      - redis
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin"
    restart: "no"

  airflow-webserver:
    build:
        context: .
        dockerfile: Dockerfile
    image: custom-airflow:2.9.1-python3.10
    env_file:
      - airflow.env
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./etls:/opt/airflow/etls
      - ./pipelines:/opt/airflow/pipelines
      - ./utils:/opt/airflow/utils
      - ./config:/opt/airflow/config
      - ./requirements.txt:/requirements.txt
    command: webserver
    depends_on:
      - airflow-init

  airflow-scheduler:
    image: custom-airflow:2.9.1-python3.10
    env_file:
      - airflow.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./etls:/opt/airflow/etls
      - ./pipelines:/opt/airflow/pipelines
      - ./utils:/opt/airflow/utils
      - ./config:/opt/airflow/config
      - ./requirements.txt:/requirements.txt
    command: scheduler
    depends_on:
      - airflow-init

  airflow-worker:
    image: custom-airflow:2.9.1-python3.10
    env_file:
      - airflow.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
      - ./etls:/opt/airflow/etls
      - ./pipelines:/opt/airflow/pipelines
      - ./utils:/opt/airflow/utils
      - ./config:/opt/airflow/config
      - ./requirements.txt:/requirements.txt
    command: celery worker
    depends_on:
      - airflow-init
